# Generated by Django 2.0.6 on 2018-06-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20180618_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_choice', models.IntegerField(choices=[(1, 'Boring'), (2, 'Engaging')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='ratings',
            field=models.ManyToManyField(to='reviews.Rating'),
        ),
    ]
