# Generated by Django 2.0.6 on 2018-06-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20180621_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_choice',
            field=models.CharField(blank=True, choices=[('Boring', 'Boring'), ('Engaging', 'Engaging')], max_length=2),
        ),
    ]
