# Generated by Django 2.0.6 on 2018-06-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20180621_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='ratings',
        ),
        migrations.AddField(
            model_name='rating',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.Chapter'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_choice',
            field=models.CharField(blank=True, choices=[('Boring', 'Boring'), ('Engaging', 'Engaging')], max_length=15),
        ),
    ]
