# Generated by Django 2.0.6 on 2018-06-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20180621_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating_choice',
            new_name='rating',
        ),
    ]
