# Generated by Django 2.0.6 on 2018-06-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20180621_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='review',
        ),
    ]
